#!/bin/sh

pkill -x idesk
sleep 0.5
if pgrep -x idesk &>/dev/null
then
  exit 1
fi

prime-run idesk & disown
while ! pgrep -x idesk &>/dev/null
do
	sleep .1
done

for id in $(xwininfo -root -children | grep '\<48x48\+' | grep 'has no name' | sed 's/^ *//' | cut -d' ' -f1)
do
	xprop -id $id -f WM_CLASS 8u -set WM_CLASS idesk
	xprop -id $id -f WM_NAME 8u -set WM_NAME idesk
done
